import type { MenuAnswer } from '@stream/wakmenu'

const commons = (file: string) => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=900`
const food = (id: string, label: string, aliases: string[], file: string): MenuAnswer => ({ id, label, aliases, imageUrl: commons(file), sourceUrl: `https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=${encodeURIComponent(label)}`, license: 'Wikimedia Commons (파일별 라이선스 확인)' })

/** Curated, editable menu starter list. Image errors intentionally fall back to the app artwork. */
export const FOOD_CATALOG: MenuAnswer[] = [
  food('pho','쌀국수',['포','베트남쌀국수'],'Pho-Beef-Noodles-2008.jpg'), food('jeyuk','제육볶음',['제육','돼지불고기'],'Jeyuk-bokkeum.jpg'), food('kimchi-stew','김치찌개',['김찌'],'Kimchi-jjigae.jpg'), food('doenjang-stew','된장찌개',['된찌'],'Doenjang-jjigae.jpg'), food('budae','부대찌개',['부찌'],'Budae_jjigae.jpg'), food('sundubu','순두부찌개',['순두부'],'Sundubu-jjigae.jpg'), food('pork-belly','삼겹살',['삼겹'],'Samgyeopsal.jpg'), food('bossam','보쌈',[],'Bossam.jpg'), food('jokbal','족발',[],'Jokbal.jpg'), food('chicken','치킨',['후라이드치킨'],'Fried_chicken.jpg'), food('pizza','피자',[],'Pizza_Margherita_stu_spivack.jpg'), food('burger','햄버거',['버거'],'Hamburger_(black_bg).jpg'), food('lotteria','롯데리아',[],'Hamburger_(black_bg).jpg'), food('momstouch','맘스터치',[],'Hamburger_(black_bg).jpg'), food('burgerking','버거킹',[],'Hamburger_(black_bg).jpg'), food('tteokbokki','떡볶이',['떡볶'],'Tteokbokki.jpg'), food('ramyeon','라면',['라면이'],'Shin_Ramyun.jpg'), food('jajangmyeon','짜장면',['짜장'],'Jajangmyeon.jpg'), food('jjamppong','짬뽕',[],'Jjamppong.jpg'), food('tangsuyuk','탕수육',['탕슉'],'Tangsuyuk.jpg'), food('mala','마라탕',[],'Malatang.jpg'), food('hotpot','훠궈',['훠거'],'Hot_pot.jpg'), food('sushi','초밥',['스시'],'Sushi_platter.jpg'), food('tonkatsu','돈가스',['돈까스'],'Tonkatsu.jpg'), food('gyudon','규동',[],'Gyudon.jpg'), food('udon','우동',[],'Kitsune_udon.jpg'), food('naengmyeon','냉면',[],'Naengmyeon.jpg'), food('kalguksu','칼국수',[],'Kalguksu.jpg'), food('seolleongtang','설렁탕',[],'Seolleongtang.jpg'), food('gukbap','국밥',[],'Dwaeji-gukbap.jpg'), food('gombap','곰탕',[],'Gomtang.jpg'), food('bibimbap','비빔밥',[],'Bibimbap.jpg'), food('gimbap','김밥',[],'Gimbap.jpg'), food('pasta','파스타',['스파게티'],'Spaghetti_carbonara.jpg'), food('steak','스테이크',[],'Steak_frites.jpg'), food('salad','샐러드',[],'Greek_salad.jpg'), food('sandwich','샌드위치',[],'Club_sandwich.png'), food('dakgalbi','닭갈비',[],'Dak-galbi.jpg'), food('jjimdak','찜닭',[],'Jjimdak.jpg'), food('gopchang','곱창',[],'Gopchang-gui.jpg'), food('daechang','대창',[],'Daechang-gui.jpg'), food('sashimi','회',['사시미'],'Sashimi.jpg'), food('curry','카레',[],'Japanese_curry_rice.jpg'),
]
